#!/usr/bin/env python3
"""Generate new_items.json for this radar run (2026-07-18 afternoon batch)."""

import json, hashlib

def make_id(url, title=""):
    s = (url or title or "").strip()
    return hashlib.sha1(s.encode()).hexdigest()[:16]

# Load seen IDs from local seen.json
with open("/home/user/market-radar/seen.json", encoding="utf-8") as f:
    seen_data = json.load(f)
seen_ids = set(seen_data.get("ids", []))

candidates = [
    # ── 大盘头条 ──────────────────────────────────────────────────────────────

    {
        "tier": 1,
        "lang": "zh",
        "markets": ["A"],
        "time": "20:00",
        "group": "大盘头条",
        "title": "长鑫科技IPO申购抽干A股流动性，上证指数大跌3.05%创近11月低点",
        "summary": "A股7月17日重挫：上证综指跌3.05%至3764点，创近11个月新低；深证成指跌5.4%。科创板史上最大IPO长鑫科技（CXMT）申购冻结巨量资金，叠加宇树科技、长鑫存储等超大型上市排队，引发市场恐慌性抛售，半导体板块领跌。",
        "why": "A股大幅调整影响港股及中概整体情绪；CXMT IPO为存储赛道重大事件，直接牵动SK海力士、美光对标估值；若持有A股科技仓位需警惕短线回撤。",
        "source": "21世纪经济报道",
        "verified": True,
        "keywords": ["A股", "长鑫科技", "CXMT", "IPO", "上证"],
        "translated": False,
        "url": "https://m.21jingji.com/article/20260717/herald/bae3c894be7033782e3f7e5cda09d01f_zaker.html",
    },
    {
        "tier": 1,
        "lang": "zh",
        "markets": ["A"],
        "time": "10:00",
        "group": "大盘头条",
        "title": "长鑫科技IPO：华尔街加密合约疯炒、估值从5792亿飙至4万亿，散户212倍超额认购",
        "summary": "长鑫科技（CXMT）7月16日以8.66元/股开启申购，募资逾579亿元，若行使绿鞋可达666亿元，成科创板第二大IPO；散户认购倍数212倍，加密合约盘前隐含估值一度达3.9万亿元，308倍PE引发争议。",
        "why": "CXMT上市将重塑A股存储赛道格局，其DRAM量产能力直接威胁SK海力士HBM主导地位；同时体量庞大的新股冻结效应已压制指数短线走势，对卖出put策略需警惕波动率突然放大。",
        "source": "新浪财经",
        "verified": True,
        "keywords": ["长鑫科技", "CXMT", "IPO", "存储芯片", "DRAM"],
        "translated": False,
        "url": "https://finance.sina.com.cn/roll/2026-07-18/doc-iniiewei8394287.shtml",
    },
    {
        "tier": 1,
        "lang": "en",
        "markets": ["US", "HK"],
        "time": "10:30",
        "group": "大盘头条",
        "title": "Kimi K3 (2.8T-parameter) launch triggers DeepSeek flashback: Nvidia -2% premarket, semiconductor ETF -20%+ from June high",
        "summary": "Moonshot AI (Alibaba-backed) released Kimi K3 on July 18 — a 2.8-trillion-parameter open-weight model beating Claude Fable 5 on Frontend Code Arena — causing Nvidia to fall ~2% premarket and the VanEck Semiconductor ETF to extend its decline to more than 20% below its late-June record. Analysts split: Patrick Moorhead called it 'an over-reaction shockingly similar to DeepSeek panic.'",
        "why": "中国AI高效模型冲击重演——影响英伟达GPU需求预期，同时利好阿里巴巴/月之暗面在AI基础设施叙事上的估值；对持有NVDA卖put头寸需关注隐含波动率（IV）短线上行风险。",
        "source": "Decrypt",
        "verified": True,
        "keywords": ["Kimi K3", "Moonshot AI", "Nvidia", "AI chip", "NVDA"],
        "translated": False,
        "url": "https://decrypt.co/373736/kimi-k3-triggered-deepseek-flashbacks-stock-market",
    },
    {
        "tier": 1,
        "lang": "en",
        "markets": ["US"],
        "time": "22:00",
        "group": "大盘头条",
        "title": "Alphabet falls 4.4%, erases $200B in market cap on Bloomberg report of Gemini 3.5 Pro delay",
        "summary": "Bloomberg reported Google is months behind schedule delivering Gemini 3.5 Pro due to capability challenges, particularly in coding. Engineers and managers fear the company risks losing market position as Anthropic and OpenAI produce superior models. GOOG closed down 4.4% on the news.",
        "why": "谷歌Gemini延迟削弱其AI竞争力叙事，利好Anthropic、OpenAI；同时削弱谷歌云广告业务估值支撑。对GOOGL持仓者信号为负。IV可能上行，卖put需谨慎。",
        "source": "Yahoo Finance / Bloomberg",
        "verified": True,
        "keywords": ["Alphabet", "GOOGL", "Gemini", "AI", "Google"],
        "translated": False,
        "url": "https://finance.yahoo.com/technology/ai/articles/alphabet-stock-falls-report-gemini-184859374.html",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "16:00",
        "group": "大盘头条",
        "title": "EU mandates Google to open Android AI features to rivals, share search data with OpenAI; upholds €4.1B antitrust fine",
        "summary": "The EU required Google to open 11 Android features to AI competitors and share data collected for search optimization with OpenAI and other AI chatbots. Separately, the European Court of Justice upheld Google's €4.1 billion Android antitrust fine, adding to regulatory pressure.",
        "why": "监管叠加对谷歌搜索广告护城河构成长期威胁；€41亿罚款落地增加法律负债。若持GOOGL需将监管风险纳入长期估值折价。",
        "source": "CNBC",
        "verified": True,
        "keywords": ["Google", "EU", "antitrust", "Alphabet", "GOOGL"],
        "translated": False,
        "url": "https://www.cnbc.com/2026/07/16/google-required-to-open-up-to-ai-search-engine-rivals-under-eu-mandated-changes.html",
    },
    {
        "tier": 1,
        "lang": "en",
        "markets": ["US"],
        "time": "08:00",
        "group": "大盘头条",
        "title": "Circle CRCL: GENIUS Act regulatory deadline hits TODAY July 18 — Fed/Treasury must issue stablecoin framework",
        "summary": "The GENIUS Act (signed July 18, 2025) gave regulators one year to issue stablecoin guidance; the deadline expires today. CRCL stock is down 30% in the past month and 66% over the past year as regulatory uncertainty weighs. Circle also received OCC approval for First National Digital Currency Bank, N.A., a positive offset.",
        "why": "监管框架落地是Circle USDC业务的关键变量——若法规严苛则合规成本上升，若宽松则利好稳定币叙事；今日为关键节点，可能引发CRCL股价波动，影响持仓者的期权时间价值。",
        "source": "crypto.news",
        "verified": True,
        "keywords": ["Circle", "CRCL", "USDC", "GENIUS Act", "stablecoin"],
        "translated": False,
        "url": "https://crypto.news/circle-faces-genius-act-test-as-crcl-stock-risks-slide/",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["US", "HK"],
        "time": "16:00",
        "group": "大盘头条",
        "title": "Gold pulls back to ~$4,016, down ~28% from January all-time high of $5,595",
        "summary": "Gold has declined sharply from its January 2026 record high, driven by hawkish Fed signals (~60% odds of a September rate hike) and elevated energy prices from Middle East tensions. Goldman Sachs year-end target remains $4,900; JPMorgan's Q4 target is $4,500.",
        "why": "金价大幅回调直接影响老铺黄金（6181.HK）和黄金珠宝板块估值；持有相关仓位需重新审视支撑；sell put策略下行风险加大。",
        "source": "Yahoo Finance",
        "verified": False,
        "keywords": ["黄金", "gold", "XAU", "金价", "老铺黄金"],
        "translated": False,
        "url": "https://finance.yahoo.com/markets/commodities/articles/gold-price-outlook-july-2026-191408891.html",
    },

    # ── 个股 ──────────────────────────────────────────────────────────────────

    {
        "tier": 1,
        "lang": "zh",
        "markets": ["HK"],
        "time": "10:00",
        "group": "个股",
        "title": "金价半年跌超28%，老铺黄金市值蒸发千亿：门店客流冷清、二手折价、按克金上架",
        "summary": "新浪7月18日实地探访老铺黄金（6181.HK）门店，发现客流明显减少，二手市场出现较大折价，部分门店开始按克定价销售，股价当日跌逾4.6%。自2025年7月高点（1102港元）至今跌幅超65%，市值蒸发逾千亿港元。",
        "why": "金价深度回调正在侵蚀老铺黄金的品牌溢价逻辑；门店客流恶化是先行指标，预示下季收入或进一步承压；持仓者需评估是否调整行权价或行权时机。",
        "source": "新浪新闻",
        "verified": True,
        "keywords": ["老铺黄金", "6181.HK", "金价", "黄金首饰", "古法金"],
        "translated": False,
        "url": "https://news.sina.com.cn/minsheng/2026-07-18/doc-iniifanf8338396.shtml",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["HK"],
        "time": "10:00",
        "group": "个股",
        "title": "Tencent's Hy3 (295B MoE) ranks #1 on OpenRouter global LLM usage with 6.13T tokens/week — beats DeepSeek, Xiaomi",
        "summary": "Tencent's Hunyuan Hy3 (released July 6 as a free open-weight model, 295B parameters, 21B active) topped OpenRouter's weekly ranking with 6.13 trillion tokens processed — surpassing DeepSeek V4 Flash (5.22T) and Xiaomi MiMo-V2.5 (5.95T). The free promotional window runs until July 21; post-window pricing is $0.14/$0.58 per M tokens.",
        "why": "Hy3跻身全球大模型使用榜首，验证腾讯AI竞争力回归，有望带动混元商业化与腾讯云AI收入预期上调；Q2财报（8月12日）前的正面催化剂。",
        "source": "TechTimes",
        "verified": True,
        "keywords": ["腾讯", "Tencent", "0700.HK", "Hy3", "混元", "AI模型"],
        "translated": False,
        "url": "https://www.techtimes.com/articles/320292/20260713/tencent-hy3-tops-openrouter-charts-base-url-swap-runs-it-free-codex-cli.htm",
    },
    {
        "tier": 2,
        "lang": "zh",
        "markets": ["HK", "US"],
        "time": "10:00",
        "group": "个股",
        "title": "阿里巴巴7月6日斥资约5000万美元回购逾410万股H股",
        "summary": "阿里巴巴-W（9988.HK）于2026年7月6日以约4999万美元回购410.87万股，延续大规模回购计划。当前分析师评级：27买入/1卖出，整体强烈买入。",
        "why": "持续回购彰显管理层信心；对持有BABA/9988期权者，回购减少流通盘有助于股价支撑，sell put策略下行安全垫略有改善。",
        "source": "搜狐财经",
        "verified": False,
        "keywords": ["阿里巴巴", "Alibaba", "9988.HK", "回购", "BABA"],
        "translated": False,
        "url": "https://www.sohu.com/a/1047115355_122123195",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["HK"],
        "time": "10:00",
        "group": "个股",
        "title": "Pop Mart surges 6.9% on World Cup MEGA LABUBU 400% edition launch (HK$1,625/unit, 1 per person)",
        "summary": "Pop Mart (9992.HK) introduced the 'MEGA LABUBU 400% World Cup 26' figure at HK$1,625, strictly limited to one per person. The limited-edition collab drove a single-day stock jump of approximately 6.9%, highlighting Labubu's continued monetization power as a flagship IP.",
        "why": "联名限定款验证Labubu IP持续吸金能力，为即将公布的业绩提供正向预期修正；段永平三度增持背书价值逻辑，对持仓者信号偏正。",
        "source": "The Standard",
        "verified": True,
        "keywords": ["泡泡玛特", "Pop Mart", "9992.HK", "Labubu", "潮玩", "MEGA"],
        "translated": False,
        "url": "https://www.thestandard.com.hk/property/article/337435/Pop-Marts-stock-price-rises-six-percent-on-World-Cup-edition-LABUBU-launch",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["HK"],
        "time": "10:00",
        "group": "个股",
        "title": "Duan Yongping raises Pop Mart stake to 7.65% (3rd top-up), becomes 2nd-largest shareholder; praises founder Wang Ning as 'Jobs-level'",
        "summary": "'China's Warren Buffett' Duan Yongping increased his Pop Mart holding to 7.65% (from 6.85%) via ~HK$1.59B purchase of ~10.59M shares at up to HK$150 each, becoming the second-largest shareholder. He stated average annual profit over the next 10-20 years is unlikely to fall below current levels, comparing founder Wang Ning's product sense to Steve Jobs.",
        "why": "大型价值投资者三度加仓具有强烈背书意义，历史上此类大股东持续增持往往领先股价修复；对市场信心修复有正向催化作用。",
        "source": "South China Morning Post",
        "verified": True,
        "keywords": ["泡泡玛特", "Pop Mart", "9992.HK", "段永平", "Labubu", "增持"],
        "translated": False,
        "url": "https://www.scmp.com/business/companies/article/3360334/what-labubu-fatigue-billionaire-investor-doubles-down-pop-mart-stake",
    },
    {
        "tier": 1,
        "lang": "en",
        "markets": ["US"],
        "time": "10:00",
        "group": "个股",
        "title": "Circle wins OCC national bank charter (First National Digital Currency Bank, N.A.) — stock rallied ~5%",
        "summary": "Circle received final approval from the OCC to operate First National Digital Currency Bank, N.A., a national trust bank. The regulatory milestone sent CRCL shares up approximately 5% on the news day and validates Circle's long-term strategy to embed USDC into the regulated banking system.",
        "why": "银行牌照批准是Circle发展史上里程碑事件，显著提升USDC合规可信度；与今日GENIUS Act截止日共同构成Circle的关键监管周——短线波动可能较大，需监控期权IV。",
        "source": "The Motley Fool",
        "verified": True,
        "keywords": ["Circle", "CRCL", "USDC", "OCC", "stablecoin", "稳定币"],
        "translated": False,
        "url": "https://www.fool.com/investing/2026/07/10/circle-just-won-a-us-national-bank-charter-heres-w/",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "10:00",
        "group": "个股",
        "title": "SK Hynix soars 13% on Nasdaq debut as SKHY; $26.5B raise is largest-ever U.S. listing by foreign company",
        "summary": "SK Hynix began trading as SKHY on the Nasdaq on July 10, 2026, after raising $26.5 billion in the largest U.S. listing by a foreign company in history. The stock surged 13% on debut, driven by HBM architecture's perceived irreplaceability in AI chip supply chains.",
        "why": "SK海力士美股上市开辟新的资金来源，同时使HBM存储供应链在美市场获得更高关注度；对相关ETF和持CSOP两倍做多SK海力士的投资者而言，估值基准上移。",
        "source": "TechTimes",
        "verified": True,
        "keywords": ["SK海力士", "SK Hynix", "HBM", "SKHY", "Nasdaq", "存储芯片"],
        "translated": False,
        "url": "https://www.techtimes.com/articles/320235/20260712/sk-hynix-soars-13-nasdaq-debut-hbm-architecture-makes-it-irreplaceable-ai-chips.htm",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "10:00",
        "group": "个股",
        "title": "SK Hynix Q2 2026 earnings due July 29: analyst projects 60.4T won operating profit (+556% YoY) but 8% below consensus; HBM4 mass production pushed to Q3",
        "summary": "Korea Investment & Securities projected SK Hynix Q2 operating profit at ~60.4 trillion won — a 556% YoY surge but ~8% below the 65T won market consensus — as full-scale HBM4 mass production was delayed from Q2 to Q3 2026. SK Hynix's Seoul shares posted their worst single session on record after the revision.",
        "why": "HBM4量产推迟移除Q2业绩上行催化剂，短线压制股价，但中期HBM供应仍偏紧；7月29日财报发布前不宜激进做多，持仓可考虑covered call锁定部分收益。",
        "source": "TechTimes",
        "verified": False,
        "keywords": ["SK海力士", "SK Hynix", "HBM4", "HBM", "业绩", "存储芯片"],
        "translated": False,
        "url": "https://www.techtimes.com/articles/320352/20260713/sk-hynix-posts-worst-seoul-session-record-hbm-contracts-limit-earnings-upside.htm",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "10:00",
        "group": "个股",
        "title": "Tesla expands Robotaxi service to Miami — first city outside Texas with fully unsupervised rides",
        "summary": "Tesla launched its unsupervised Full Self-Driving Robotaxi service in Miami, Florida, operating Model Y vehicles with no safety personnel. This marks the first expansion outside Texas (Austin, Dallas, Houston) and the first time Unsupervised FSD operates at scale outside the original market.",
        "why": "Robotaxi扩城是特斯拉FSD商业化落地的实质里程碑，有助于重建市场对自动驾驶收入预期的信心；但股东质疑时间表持续推迟，需关注7月下旬的财报指引。",
        "source": "Tesla Oracle",
        "verified": True,
        "keywords": ["特斯拉", "Tesla", "TSLA", "Robotaxi", "FSD", "自动驾驶"],
        "translated": False,
        "url": "https://www.teslaoracle.com/2026/07/14/tesla-expands-robotaxi-service-to-miami-watch-the-first-impressions-of-users/",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "10:00",
        "group": "个股",
        "title": "Palantir wins U.S. Army NGC2 contract — largest data modernization award; Q1 2026 U.S. Gov revenue +84% to $687M",
        "summary": "The U.S. Army chose Palantir's Foundry as the core cloud data layer for its NGC2 modernization program, transitioning from prototype to wide deployment. Earlier, Palantir and Nvidia announced a collaboration pairing AIP/Foundry with Nvidia Nemotron AI models. Q1 2026 revenue reached $1.633B (+85% YoY), with full-year guidance raised to ~$7.65B.",
        "why": "政府合同持续落地支撑PLTR高估值叙事；Nvidia合作将AI平台推向更多政企场景，有望加速商业化。持仓者可关注财报前的期权IV水平。",
        "source": "Yahoo Finance",
        "verified": True,
        "keywords": ["Palantir", "PLTR", "AIP", "Foundry", "AI平台", "政府合同"],
        "translated": False,
        "url": "https://finance.yahoo.com/markets/stocks/articles/palantir-just-secured-u-army-180024842.html",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "10:00",
        "group": "个股",
        "title": "Intel 18A-P moves to risk production; foundry yield rises to 85%; Nvidia and OpenAI among confirmed customers",
        "summary": "Intel Foundry announced that Intel 18A-P (the performance-enhanced variant of 18A) has entered risk production on schedule. Foundry yield has improved from 65% to 85%, and Intel has secured orders from Nvidia, AMD, Marvell, Microsoft, Micron, and OpenAI. The process node offers up to 9% higher performance or 18% lower power versus base 18A.",
        "why": "18A良率大幅提升并获Nvidia/OpenAI订单，是英特尔代工转型最重要的正面信号；若商业良率如期于2026年末达标，将显著改善代工业务亏损局面，有助于股价修复。",
        "source": "Yahoo Finance / Intel",
        "verified": True,
        "keywords": ["英特尔", "Intel", "INTC", "18A", "foundry", "晶圆代工"],
        "translated": False,
        "url": "https://finance.yahoo.com/technology/articles/intel-intc-foundry-advances-intel-102246680.html",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "10:00",
        "group": "个股",
        "title": "EU's €3/package e-commerce fee (from July 1) hits Temu and Shein hard — 150-euro customs exemption abolished",
        "summary": "From July 1, 2026, the EU levies a flat €3 fee per tariff classification on all third-country e-commerce packages AND abolished the previous €150 customs-free threshold. Temu and Shein are most impacted as their model relies on direct-from-China shipments. Temu's response: expand semi-managed model and increase overseas bulk shipping to mitigate costs.",
        "why": "欧盟监管直接压缩Temu欧洲市场利润率，PDD需加快海外本地化和供应链调整以维持价格优势；对持仓者而言这是渐进式监管成本，需关注下季欧洲收入占比变化。",
        "source": "E-Commerce Institute Cologne",
        "verified": True,
        "keywords": ["拼多多", "Temu", "PDD", "跨境电商", "欧盟", "关税"],
        "translated": False,
        "url": "https://ecommerceinstitut.de/eu-package-fee-from-1-july-2026-what-the-new-customs-rules-mean-for-temu-shein-and-european-e-commerce/",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "10:00",
        "group": "个股",
        "title": "SanDisk SNDK: Goldman raises target to $2,200; Motley Fool projects $3,000 by year-end; NAND supply tight into 2027",
        "summary": "Goldman Sachs raised its SanDisk (SNDK) price target to $2,200 (from $1,200) on July 5, citing continued NAND supply tightness. The Motley Fool (July 15) projected $3,000 by year-end. SanDisk has surged ~4,885% since its February 2025 Nasdaq debut. Q4 FY2026 earnings are due August 5.",
        "why": "NAND价格持续紧张叠加分析师目标价大幅上调，对持有SNDK仓位的投资者是正向信号；8月5日财报为下一关键催化点，可考虑在财报前布局sell put以赚取时间价值。",
        "source": "The Motley Fool",
        "verified": False,
        "keywords": ["闪迪", "SanDisk", "SNDK", "NAND", "闪存", "存储"],
        "translated": False,
        "url": "https://www.fool.com/investing/2026/07/15/prediction-sandisk-stock-is-going-to-hit-3000-by-t/",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "10:00",
        "group": "个股",
        "title": "Disney 'Moana' live-action misfires with $43M U.S. opening — down 38% vs. prior weekend market",
        "summary": "Disney's live-action 'Moana' remake opened to just $43M domestically, significantly underperforming expectations as the entire marketplace was down 38% from the prior weekend. The result raises questions about Disney's live-action remake strategy and franchise monetization.",
        "why": "Moana开局不佳令市场对迪士尼票房回升预期降温；迪士尼内容+流媒体商业模式受质疑，短线股价承压；对DIS持仓者需关注管理层是否下调内容指引。",
        "source": "Deadline",
        "verified": True,
        "keywords": ["迪士尼", "Disney", "DIS", "票房", "Moana", "streaming"],
        "translated": False,
        "url": "https://deadline.com/2026/07/box-office-moana-1236979144/",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "10:00",
        "group": "个股",
        "title": "Interactive Brokers (IBKR) Q2 2026 earnings due July 21; consensus EPS $0.59 (+15.7% YoY), revenue $1.66B (+12.2%)",
        "summary": "Interactive Brokers scheduled Q2 2026 results for July 21 at 4:00pm ET. Analysts expect EPS of $0.59 (+15.7% YoY) and revenue of $1.66B (+12.2% YoY), driven by higher client account growth and volatility-boosted DARTs. The company beat consensus in 3 of the last 4 quarters.",
        "why": "IBKR财报（3天后）是盈透证券持仓者的近期关键催化点；客户资产增长和交易量数据可作为市场整体交易活跃度的先行指标，亦可参考富途（FUTU）的业绩预判。",
        "source": "StockTitan",
        "verified": True,
        "keywords": ["盈透证券", "Interactive Brokers", "IBKR", "业绩", "券商"],
        "translated": False,
        "url": "https://www.stocktitan.net/news/IBKR/interactive-brokers-group-to-host-second-quarter-earnings-conference-mccq54ofjw7r.html",
    },
    {
        "tier": 2,
        "lang": "en",
        "markets": ["HK"],
        "time": "10:00",
        "group": "个股",
        "title": "Meituan earnings call: Keeta Saudi Arabia nearing month-1 profitability; Q1 2026 revenue CNY91B (+5.6%), net loss CNY6.8B",
        "summary": "Meituan's earnings call highlighted that Keeta's Saudi Arabia operations are expected to achieve profitability within their first full month of operation. Q1 2026 saw revenue rise 5.6% YoY to CNY91B, but a net swing to a CNY6.8B loss (vs. CNY10.1B profit a year ago) due to intensified competition and overseas spending. Full-year new-business losses expected below 2025 levels.",
        "why": "Keeta出海盈利节点提前是重要积极信号——验证海外扩张可行性，有助于收窄估值折价；国内业务竞争激烈仍是短期压力，关注下一季Keeta利润数据改善节奏。",
        "source": "Futu News",
        "verified": False,
        "keywords": ["美团", "Meituan", "3690.HK", "Keeta", "业绩", "出海"],
        "translated": False,
        "url": "https://news.futunn.com/en/post/70670660/meituan-earnings-call-firmly-oppose-internal-competition-not-in-a",
    },
    {
        "tier": 3,
        "lang": "en",
        "markets": ["US"],
        "time": "10:00",
        "group": "个股",
        "title": "DeepSeek developing in-house AI chip for inference workloads, reducing reliance on Nvidia GPUs",
        "summary": "Reports indicate DeepSeek is designing its own semiconductor focused on inference workloads — a move that could reduce dependency on Nvidia hardware. The chip is still in development and would primarily serve DeepSeek's own inference needs at scale.",
        "why": "DeepSeek自研芯片若成真，长期削弱Nvidia在中国推理市场的需求；配合Kimi K3冲击，中国AI自给自足叙事持续强化，对NVDA的中国收入预期构成下行压力。",
        "source": "Yahoo Finance",
        "verified": False,
        "keywords": ["DeepSeek", "Nvidia", "NVDA", "AI芯片", "GPU", "推理"],
        "translated": False,
        "url": "https://finance.yahoo.com/technology/ai/articles/nvidia-shares-edge-lower-report-131018662.html",
    },
]

# Assign IDs and deduplicate
for item in candidates:
    item["id"] = make_id(item["url"], item.get("title", ""))

# Filter out already-seen items
fresh = [it for it in candidates if it["id"] not in seen_ids]

print(f"Total candidates: {len(candidates)}")
print(f"Already seen (discarded): {len(candidates) - len(fresh)}")
print(f"New items to publish: {len(fresh)}")
for it in fresh:
    print(f"  [{it['tier']}] {it['title'][:70]}")

with open("/home/user/market-radar/new_items.json", "w", encoding="utf-8") as f:
    json.dump(fresh, f, ensure_ascii=False, indent=2)

print(f"\nnew_items.json written with {len(fresh)} items.")
