import json, hashlib

def make_id(url, title):
    s = (url or title or "").strip()
    return hashlib.sha1(s.encode()).hexdigest()[:16]

items = [
    # ============ 大盘头条 ============
    {
        "id": make_id("https://www.cnbc.com/2026/06/24/sk-hynix-nasdaq-adr-listing-south-korea.html", ""),
        "tier": 1,
        "lang": "en",
        "markets": ["US", "HK"],
        "time": "09:30",
        "group": "大盘头条",
        "title": "SK Hynix Lists ADRs on Nasdaq (SKHY), Raises ~$28B in Largest-Ever ADR Offering",
        "summary": "SK Hynix listed on Nasdaq July 10 under ticker SKHY, raising ~$28B (₩43T), the largest ADR in Wall Street history. Proceeds earmarked for Yongin semiconductor cluster and ASML EUV machines. Shares dropped 17%+ in early July before recovering. HBM market share: SK Hynix ~50–55%, Samsung ~35–40%, Micron ~5–10%.",
        "why": "直接影响持仓中SK海力士HK ADR(7709.HK)及南方两倍做多；SKHY纳斯达克挂牌打通国际机构资金，有助于消除韩国折价；HBM4供应格局影响英伟达GPU及美光(MU)竞争研判，期权隐含波动率关注。",
        "source": "CNBC / Yahoo Finance",
        "verified": True,
        "keywords": ["SK海力士", "SK Hynix", "SKHY", "HBM", "HBM4", "DRAM", "存储芯片"],
        "translated": False,
        "url": "https://www.cnbc.com/2026/06/24/sk-hynix-nasdaq-adr-listing-south-korea.html"
    },
    {
        "id": make_id("https://finance.sina.com.cn/stock/usstock/c/2026-07-09/doc-inihesme4510809.shtml", ""),
        "tier": 1,
        "lang": "zh",
        "markets": ["US"],
        "time": "09:00",
        "group": "大盘头条",
        "title": "美联储6月FOMC会议纪要显示鹰鸽分歧并存，7月29日FOMC约25%概率加息",
        "summary": "美联储7月9日公布6月16-17日FOMC会议纪要，在新主席沃什首场主持会议上全体一致维持利率3.5%-3.75%。纪要显示：部分官员认为通胀将进一步放缓（为降息创造空间），另部分认为价格上涨压力仍高（或需加息）。市场目前预期7月29日会议约25%概率加息，75%概率维持不变。",
        "why": "美联储利率路径直接影响港美股估值；加息概率上升压制成长股期权卖出策略（sell put风险上升）；黄金、科技股、稳定币板块均受波及。",
        "source": "新浪财经",
        "verified": True,
        "keywords": ["美联储", "FOMC", "货币政策", "加息", "宏观"],
        "translated": False,
        "url": "https://finance.sina.com.cn/stock/usstock/c/2026-07-09/doc-inihesme4510809.shtml"
    },
    {
        "id": make_id("https://finance.sina.com.cn/stock/t/2026-07-09/doc-inihfpqx5341394.shtml", ""),
        "tier": 1,
        "lang": "zh",
        "markets": ["HK"],
        "time": "10:00",
        "group": "大盘头条",
        "title": "港股大模型双雄解禁大考：智谱两日涨超20%，MiniMax单日暴跌17.98%",
        "summary": "7月8-9日智谱(2498.HK)与MiniMax(2473.HK)首批限售股解禁。智谱解禁约25.68亿股（5.76%，市值超400亿港元），却逆市收涨13.35%续涨11.34%；MiniMax解禁15.3亿股（48.9%），单日暴跌17.98%至297.4港元。7月10日港股AI板块集体承压，恒生科技指数早市涨2.7%后大幅收窄。",
        "why": "解禁潮考验港股AI大模型板块筹码结构稳定性；智谱/MiniMax的分化走势将影响AI估值逻辑及腾讯、阿里等大市值科技股的资金轮动。",
        "source": "新浪财经",
        "verified": True,
        "keywords": ["港股", "恒生科技指数", "智谱", "MiniMax", "解禁", "大模型"],
        "translated": False,
        "url": "https://finance.sina.com.cn/stock/t/2026-07-09/doc-inihfpqx5341394.shtml"
    },
    {
        "id": make_id("https://finance.biggo.com/news/d7bc5846-daa4-40a0-a08c-ed9f1f319cc8", ""),
        "tier": 2,
        "lang": "en",
        "markets": ["HK"],
        "time": "09:30",
        "group": "大盘头条",
        "title": "Seven IPOs Flood HK Exchange in One Day; Goldman Sachs Projects Full-Year HK IPO Fundraising Could Hit Record $60B",
        "summary": "On July 9, HKEX hosted seven simultaneous IPO debuts, the busiest IPO day of 2026. Luxshare Precision raised ~HK$24.3B with 26 cornerstone investors. Goldman Sachs says HK stocks have 'entered the AI era' and forecasts full-year IPO fundraising could hit a record $60B. Hang Seng Index slipped 0.7% to 24,030 on July 9.",
        "why": "港股IPO生态活跃度是市场健康信号，拉动整体流动性；立讯精密(苹果供应链)上市与AI企业扎堆挂牌，共同提升恒生科技指数成分股体量，间接影响持仓港股的资金面。",
        "source": "BigGo Finance / Goldman Sachs",
        "verified": False,
        "keywords": ["港股", "IPO", "恒生指数", "立讯精密"],
        "translated": False,
        "url": "https://finance.biggo.com/news/d7bc5846-daa4-40a0-a08c-ed9f1f319cc8"
    },
    {
        "id": make_id("https://www.bls.gov/news.release/archives/cpi_06102026.htm", ""),
        "tier": 1,
        "lang": "en",
        "markets": ["US"],
        "time": "08:30",
        "group": "大盘头条",
        "title": "US May CPI +4.2% YoY; June CPI Report Due July 14 — Key Input for Fed's July 29 Meeting",
        "summary": "May 2026 CPI rose 0.5% MoM and 4.2% YoY (energy +3.9% accounted for >60% of increase; core CPI +2.82% YoY). The June 2026 CPI report is scheduled for release July 14 at 8:30AM ET — a critical data point before the FOMC July 28-29 meeting where markets price a 25% chance of a rate hike.",
        "why": "CPI走向直接决定美联储7月29日是否加息；通胀超预期则可能触发加息，引发成长股下行压力及sell put风险敞口扩大；持仓标的中高估值的科技股（NVDA、PLTR、TSLA）对加息最为敏感。",
        "source": "U.S. Bureau of Labor Statistics",
        "verified": True,
        "keywords": ["CPI", "美联储", "通胀", "宏观", "macro"],
        "translated": False,
        "url": "https://www.bls.gov/news.release/archives/cpi_06102026.htm"
    },
    {
        "id": make_id("https://cryptoslate.com/genius-act-deadline-puts-stablecoin-issuers-on-the-clock/", ""),
        "tier": 1,
        "lang": "en",
        "markets": ["US"],
        "time": "00:00",
        "group": "大盘头条",
        "title": "GENIUS Act Stablecoin Rules Due July 18: Six Agencies Racing to Finalize Framework; Big Banks May Issue Own Stablecoins",
        "summary": "Six federal agencies (OCC, FDIC, NCUA, Treasury, FinCEN, OFAC) must finalize GENIUS Act stablecoin rules by July 18, 2026. The law requires highly liquid government-asset reserves, monthly audits, AML compliance, and bans interest payments. Circle's USDC ($73.7B in circulation) is already compliant; mid-size issuers face existential compliance cost burden. Post-July 18, large banks may be cleared to issue their own stablecoins.",
        "why": "7月18日是GENIUS法案监管框架落地的关键节点，将直接影响Circle(CRCL)与USDC竞争格局；若大银行获准入场，Circle的市场份额面临压力，同时稳定币赛道合规红利利好USDC已实质合规的优势地位；期权sell put短期波动率需关注。",
        "source": "CryptoSlate / Stablecoin Insider",
        "verified": True,
        "keywords": ["Circle", "USDC", "稳定币", "stablecoin", "GENIUS Act", "稳定币法案"],
        "translated": False,
        "url": "https://cryptoslate.com/genius-act-deadline-puts-stablecoin-issuers-on-the-clock/"
    },

    # ============ 个股 ============
    {
        "id": make_id("https://www.fool.com/investing/2026/07/06/why-did-tesla-stock-jump-today/", ""),
        "tier": 1,
        "lang": "en",
        "markets": ["US"],
        "time": "06:00",
        "group": "个股",
        "title": "Tesla Q2 Deliveries Hit 480,126 Units (+25% YoY), Crushing Estimates; Robotaxi Expands to Miami Without Safety Driver",
        "summary": "Tesla reported 480,126 Q2 2026 deliveries (+25% YoY), far exceeding Wall Street's ~406K consensus. Production was ~452K units; energy storage 13.5 GWh. Stock jumped 6.62% on July 6. Separately, Tesla expanded its Robotaxi service to Miami — first city without an on-board human safety monitor. RBC raised price target to $500 from $475. Q2 earnings due July 22.",
        "why": "Q2交付量大超预期+Robotaxi无人化突破是双重催化剂；FSD商业化进度加速，直接支撑TSLA估值重估；Q2财报7月22日即将到来，可关注sell put时间窗口；Optimus/储能业务值得在财报中重点跟踪。",
        "source": "The Motley Fool / StocksToTrade",
        "verified": True,
        "keywords": ["特斯拉", "Tesla", "TSLA", "Robotaxi", "FSD", "自动驾驶"],
        "translated": False,
        "url": "https://www.fool.com/investing/2026/07/06/why-did-tesla-stock-jump-today/"
    },
    {
        "id": make_id("https://www.yicai.com/news/102996468.html", ""),
        "tier": 1,
        "lang": "zh",
        "markets": ["HK"],
        "time": "10:00",
        "group": "个股",
        "title": "阿里巴巴"淘宝闪购"力争第一，市占率45.2%逼平美团，即时零售大战白热化",
        "summary": "2026年中国即时零售市场规模突破万亿元。淘宝闪购市占率达45.2%，仅落后美团0.2个百分点（美团外卖市占从73%降至50%，阿里系升至42%）。淘宝闪购7月2日上线两月日订单突破6000万，美团即时零售7月5日日订单破1.2亿。阿里宣布坚定加大投入，本季度即时零售收入劲增56%。",
        "why": "即时零售决战直接关系美团(3690.HK)和阿里巴巴(9988.HK)的收入结构与估值逻辑；美团丧失市占护城河对其sell put行权价构成下行风险；阿里AI+商业协同效应若持续验证则支撑估值重估。",
        "source": "第一财经",
        "verified": False,
        "keywords": ["阿里巴巴", "美团", "淘宝", "即时零售", "美团闪购", "外卖"],
        "translated": False,
        "url": "https://www.yicai.com/news/102996468.html"
    },
    {
        "id": make_id("https://finance.sina.com.cn/roll/2026-07-08/doc-inihapna8011193.shtml", ""),
        "tier": 2,
        "lang": "zh",
        "markets": ["HK"],
        "time": "14:00",
        "group": "个股",
        "title": "AI商业化破局提振港股科技股，阿里巴巴大涨超12%，千问大模型月活突破3亿",
        "summary": "7月8日港股科技股迎重大行情，阿里巴巴(9988.HK)午后放量拉升盘中涨幅超12%，触及107.7港元，创2025年9月以来最大单日涨幅，成交额超110亿港元。阿里Qwen3.6-Plus等多款新模型推出，千问大模型单日调用量突破1.4万亿Token，C端月活用户破3亿。",
        "why": "AI商业化路径明朗推动港股科技估值逻辑重构；阿里AI+商业双轮驱动已被市场认可；持仓阿里考虑sell call时机（高位获利），或关注技术调整后的新buy put level。",
        "source": "新浪财经",
        "verified": False,
        "keywords": ["阿里巴巴", "Alibaba", "通义千问", "阿里云", "港股"],
        "translated": False,
        "url": "https://finance.sina.com.cn/roll/2026-07-08/doc-inihapna8011193.shtml"
    },
    {
        "id": make_id("https://247wallst.com/investing/2026/07/08/palantir-just-hit-300-billion-the-numbers-say-thats-only-the-start/", ""),
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "08:00",
        "group": "个股",
        "title": "Palantir Hits $300B Market Cap; DA Davidson Upgrades to Buy, Target $175; Q1 Revenue +85% YoY",
        "summary": "Palantir (PLTR) market cap exceeded $300B (stock ~$129.30 as of July 2 vs. $177.75 YTD start, -27.26% YTD). DA Davidson upgraded to Buy, raised target to $175. Q1 2026 revenue $1.632B, +85% YoY — highest growth rate since IPO. Rule of 40 score: 145%. FY2026 revenue guidance raised to +71% YoY. Q2 earnings due August 3.",
        "why": "Palantir是国防AI+政府合同的纯粹标的；市值破3000亿且机构升级评级，支撑当前sell put策略；Q2财报8月3日前隐含波动率有望抬升，为期权策略提供时间价值收入机会。",
        "source": "24/7 Wall St. / DA Davidson",
        "verified": True,
        "keywords": ["Palantir", "PLTR", "AIP", "国防AI", "AI平台"],
        "translated": False,
        "url": "https://247wallst.com/investing/2026/07/08/palantir-just-hit-300-billion-the-numbers-say-thats-only-the-start/"
    },
    {
        "id": make_id("https://simplywall.st/stocks/us/tech/nasdaq-sndk/sandisk/news/sandisk-sndk-lands-meta-supply-deal-for-its-ai-infrastructur", ""),
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "07:00",
        "group": "个股",
        "title": "SanDisk Secures Multi-Year NAND Supply Deal With Meta for AI Infrastructure; BiCS10 Tech Announced",
        "summary": "SanDisk (SNDK) signed a multi-year NAND flash memory supply agreement with Meta Platforms, naming it a key supplier for Meta's AI computing buildout through 2026+. Separately, SanDisk announced BiCS10 1Tb TLC NAND sampling — density +59%, interface speed +33% to 4.8Gb/s. Revenue surged 251% YoY to $6.0B with 78.4% gross margins. Stock down 24% in July after doubling in H1.",
        "why": "SNDK获Meta多年AI基础设施订单是闪存赛道AI需求最直接的验证；BiCS10技术领先；但7月股价-24%的回调提供潜在sell put机会（评估行权价支撑）；与美光(MU)竞争格局亦受此影响。",
        "source": "Simply Wall St / Motley Fool",
        "verified": False,
        "keywords": ["闪迪", "SanDisk", "SNDK", "NAND", "闪存", "固态硬盘"],
        "translated": False,
        "url": "https://simplywall.st/stocks/us/tech/nasdaq-sndk/sandisk/news/sandisk-sndk-lands-meta-supply-deal-for-its-ai-infrastructur"
    },
    {
        "id": make_id("https://www.trefis.com/stock/intc/articles-v3/605903/intels-500-billion-question-where-are-foundry-proof-points/2026-07-07", ""),
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "08:00",
        "group": "个股",
        "title": "Intel 18A Foundry Yields Seen Slipping to Late 2026/2027; INTC Down ~16% in 7 Sessions; July 23 Earnings a Litmus Test",
        "summary": "Intel (INTC) stock fell to ~$109.68 on July 10 (down ~16% in 7 sessions) as reports suggest 18A process profitability could slip to late 2026 or 2027. External foundry revenue remains minimal at $174M despite $5.4B total foundry revenue. Perplexity AI chose Nvidia's Vera chip over Intel's Gaudi 3, highlighting AI performance gaps. Q1 foundry revenue +$0.7B YoY. July 23 earnings are a critical test.",
        "why": "英特尔代工业务（18A）若持续延误，直接削弱其唯一潜在颠覆性催化剂；Gaudi 3被Perplexity放弃是客户验证失败的负面信号；7月23日财报前期权隐含波动率或上升，可关注protective put策略。",
        "source": "Trefis / FX Leaders / TradingKey",
        "verified": False,
        "keywords": ["英特尔", "Intel", "INTC", "晶圆代工", "foundry", "18A", "Gaudi"],
        "translated": False,
        "url": "https://www.trefis.com/stock/intc/articles-v3/605903/intels-500-billion-question-where-are-foundry-proof-points/2026-07-07"
    },
    {
        "id": make_id("https://investor.costco.com/news/news-details/2026/Costco-Wholesale-Corporation-Reports-June-Sales-Results-and-Announces-Quarterly-Cash-Dividend/default.aspx", ""),
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "16:15",
        "group": "个股",
        "title": "Costco June Net Sales +10.6% to $29.24B; Digital Sales +20.9%; Declares $1.47/Share Quarterly Dividend",
        "summary": "Costco (COST) reported June 2026 (5 weeks ended July 5) net sales of $29.24B, up 10.6% YoY. Digitally-enabled sales grew 20.9%. Comparable store sales: US +10.6%, Canada +3.7%, Other International +4.7%, Total Company +8.8%. Board declared quarterly dividend of $1.47/share, payable August 7, 2026.",
        "why": "好市多业绩超预期+强劲分红，是消费赛道会员模式韧性的持续验证；美股消费板块稳定性支持sell put策略（COST波动率通常低）；数字化+20.9%增速暗示全渠道消费持续。",
        "source": "Costco Investor Relations (Official)",
        "verified": True,
        "keywords": ["好市多", "Costco", "COST", "会员店"],
        "translated": False,
        "url": "https://investor.costco.com/news/news-details/2026/Costco-Wholesale-Corporation-Reports-June-Sales-Results-and-Announces-Quarterly-Cash-Dividend/default.aspx"
    },
    {
        "id": make_id("https://www.gurufocus.com/news/8944672/nvidias-ai-compute-partnership-boosts-cloud-firms-stock-ticker-nvda", ""),
        "tier": 2,
        "lang": "en",
        "markets": ["US"],
        "time": "07:00",
        "group": "个股",
        "title": "Nvidia Launches AI Compute Partnership (AICP) for Cloud Firms; NVDA Down ~18% From June High Near $195",
        "summary": "Nvidia (NVDA) announced its AI Compute Partnership (AICP) initiative July 4 to support emerging cloud firms in acquiring AI chips. Also released Nemotron 3 Ultra (lower-cost AI model) and expanded GeForce NOW with RTX 5080 servers. Despite strong fundamentals, NVDA has fallen ~18% from its June high, trading near $195, making it the worst performer in its own chip group YTD. Q2 earnings due late August.",
        "why": "英伟达是AI芯片核心持仓；AICP扩大AI算力下游生态，长期利好；但股价较高点回调18%需关注支撑位，当前或为sell put的合适时机窗口（评估$170-180行权价）；财报前波动率预计上升。",
        "source": "GuruFocus / NVIDIA Newsroom",
        "verified": False,
        "keywords": ["英伟达", "Nvidia", "NVDA", "GPU", "AI芯片", "数据中心", "黄仁勋"],
        "translated": False,
        "url": "https://www.gurufocus.com/news/8944672/nvidias-ai-compute-partnership-boosts-cloud-firms-stock-ticker-nvda"
    },
    {
        "id": make_id("https://www.thestandard.com.hk/finance/article/336810/Zhipu-AI-and-other-major-tech-firms-raise-68-billion-in-share-placement", ""),
        "tier": 2,
        "lang": "en",
        "markets": ["HK"],
        "time": "11:00",
        "group": "个股",
        "title": "MiniMax Completes HK$16B Financing Round; 80% Allocated to AI Infrastructure and Model R&D",
        "summary": "On July 10, MiniMax (2473.HK) completed a new HK$16B financing round attracting top international sovereign funds, long-term institutional investors, and Chinese institutions. 80% of net proceeds earmarked for AI infrastructure and model R&D. Separately, Zhipu AI (2513.HK) launched a HK$31.4B share placement at HK$1,588/share (12.99% discount to Wednesday close).",
        "why": "港股AI大模型融资接连落地，夯实了AI赛道长期资本属性；MiniMax主权基金背书提升信用背书；但解禁后Zhipu/MiniMax的高折价配售对市价构成短期摊薄压力，持有恒生科技相关ETF需关注。",
        "source": "The Standard HK",
        "verified": False,
        "keywords": ["港股", "MiniMax", "大模型", "AI"],
        "translated": False,
        "url": "https://www.thestandard.com.hk/finance/article/336810/Zhipu-AI-and-other-major-tech-firms-raise-68-billion-in-share-placement"
    },
    {
        "id": make_id("https://wallstreetcn.com/articles/3768449", ""),
        "tier": 1,
        "lang": "zh",
        "markets": ["US"],
        "time": "09:00",
        "group": "个股",
        "title": "拼多多Q1财报大幅低于预期，Temu遭欧盟2亿欧元罚款，中国监管约谈618虚假广告",
        "summary": "PDD Holdings Q1 2026 EPS 9.51元，较预期16.77元低43%；营收1062亿元低于预期3.3%，股价单日跌7.6%。Temu在欧盟被罚款2亿欧元（5月），法国通过针对Temu的快时尚法案。中国监管6月11日约谈拼多多等平台就618"虚假广告"问题，叠加中国政府持续调查。下季报定于8月31日。",
        "why": "拼多多出海（Temu）遭欧盟重罚叠加国内监管收紧，双重压制成长预期；Q1大幅miss后，估值底部需重新评估；下季报前隐含波动率高，期权策略须谨慎；跨境电商合规成本上升也影响整体竞争格局。",
        "source": "华尔街见闻",
        "verified": True,
        "keywords": ["拼多多", "PDD", "Temu", "跨境电商", "百亿补贴"],
        "translated": False,
        "url": "https://wallstreetcn.com/articles/3768449"
    },
    {
        "id": make_id("https://finance.sina.com.cn/wm/2026-07-07/doc-inifyquv1581571.shtml", ""),
        "tier": 2,
        "lang": "zh",
        "markets": ["HK"],
        "time": "09:00",
        "group": "个股",
        "title": "蜜雪冰城(2097.HK)股价年内接近腰斩，香港门店收缩，海外扩张模式受考验",
        "summary": "蜜雪冰城港股7月7日盘中低见208港元，年内跌幅接近50%。香港门店因租金高企导致单店盈利难以闭环，公司战略收缩香港/澳门不盈利门店。但基本面仍稳健：2025年净利润+32.7%至58.9亿元，全球门店达59,823家（净增13,344家）。2026年策略转向放缓开店、优化单店模型。",
        "why": "蜜雪冰城港股大幅回调后，估值已显著压缩，值得重评基本面；出海收缩若成趋势将影响长期增长叙事；低价模式在高租金市场的局限性也为判断其覆盖call策略提供参考。",
        "source": "新浪财经",
        "verified": False,
        "keywords": ["蜜雪冰城", "蜜雪", "Mixue", "现制茶饮", "新茶饮"],
        "translated": False,
        "url": "https://finance.sina.com.cn/wm/2026-07-07/doc-inifyquv1581571.shtml"
    },
    {
        "id": make_id("https://k.sina.com.cn/article_7880068201_1d5b04c69068027iy8.html", ""),
        "tier": 2,
        "lang": "zh",
        "markets": ["HK"],
        "time": "10:00",
        "group": "个股",
        "title": "小米新子品牌"澎程"正式发布，瞄准增程大型SUV（20–45万元），直面理想/华为赛道",
        "summary": "小米集团(1810.HK)发布新子品牌"SkyNomad小米澎程"，定位大型增程式SUV，预计售价区间20万至45万元，直接竞争理想L系列、华为问界M系列。YU7连续六个月蝉联全价位SUV销量冠军（2月单月20,196辆）；7月购车权益最高达7.9万元。",
        "why": "澎程子品牌拓宽小米汽车价格带至高端，有助于提升单车毛利率；新赛道能否顺利拓展是2026年下半年业绩关键变量；持仓1810.HK可考虑在新品发布消化期关注波动率动态并评估sell put时机。",
        "source": "新浪新闻",
        "verified": False,
        "keywords": ["小米", "Xiaomi", "YU7", "小米汽车", "雷军"],
        "translated": False,
        "url": "https://k.sina.com.cn/article_7880068201_1d5b04c69068027iy8.html"
    },
    {
        "id": make_id("https://36kr.com/p/3875690969640969", ""),
        "tier": 3,
        "lang": "zh",
        "markets": ["HK"],
        "time": "10:00",
        "group": "个股",
        "title": "泡泡玛特上半年"踩刹车"，SKULLPANDA×Robert Wun巴黎时装周联名破圈，品牌高端化加速",
        "summary": "2026年上半年潮玩市场泡泡玛特(9992.HK)"踩刹车"——部分新品复制爆款难度加大，同期上海PTS玩具展取消（7月原本计划）。但SKULLPANDA联名英国设计师Robert Wun于7月8日巴黎时装周发布，是品牌历史首次跻身顶级时装周，高端化里程碑意义显著。",
        "why": "泡泡玛特巴黎时装周联名是高端化品牌破圈的里程碑；有助于提升IP溢价和国际能见度；但上半年基本面走弱需要观察Q2财报数据来重评增长预期；持仓可考虑联名催化后的covered call策略。",
        "source": "36氪",
        "verified": False,
        "keywords": ["泡泡玛特", "Pop Mart", "POPMART", "Skullpanda", "Labubu", "潮玩"],
        "translated": False,
        "url": "https://36kr.com/p/3875690969640969"
    },
    {
        "id": make_id("https://news.qq.com/rain/a/20260706A02HJP00", ""),
        "tier": 2,
        "lang": "zh",
        "markets": ["HK"],
        "time": "09:00",
        "group": "个股",
        "title": "国际金价7月约4116美元/盎司，中国央行6月增持黄金创2.5年最大单月增量",
        "summary": "7月国际现货金价约4116.39美元/盎司（7月10日），7月6日曾达4030-4100区间；国内黄金T+D约910.7元/克，零售金价约1260-1263元/克。中国人民银行6月增持黄金储备创2.5年来最大单月增量，央行持续增持成为金价支撑关键力量。地缘紧张（美伊冲突）叠加美联储利率不确定性维持金价高位。",
        "why": "黄金高位徘徊直接影响老铺黄金(6181.HK)业绩与估值（古法金首饰的金价传导）；老铺黄金2026年首次调价幅度20%-30%；央行增持是中期金价底部支撑；持仓可关注老铺黄金受益于金价高位的盈利超预期可能。",
        "source": "腾讯财经",
        "verified": False,
        "keywords": ["老铺黄金", "Laopu Gold", "黄金", "金价", "珠宝", "黄金首饰"],
        "translated": False,
        "url": "https://news.qq.com/rain/a/20260706A02HJP00"
    },
]

with open("new_items.json", "w", encoding="utf-8") as f:
    json.dump(items, f, ensure_ascii=False, indent=2)

print(f"生成 {len(items)} 条新闻条目到 new_items.json")
for item in items:
    print(f"  [{item['tier']}] {item['group']} | {item['title'][:60]}... | id={item['id']}")
